# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483d76a8a86664059a2e5f6c11891d42e1e73021b90f5054f36947c246956359707cdab6d5b326eedfdb9c172230c8495a9c98a114b87855a645e79925e7c477

test:
  secret_key_base: 073cb723ca7d46b319ec1d977721049ddbd2928239c86a3ac555d05c09f6fb26f96ed96e3308b15f7d87b7ca8c04e1a293c021d216ed448a609b4b78e22881dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
